apiVersion: batch/v1
kind: Job
metadata:
  name: nim-download-profile-job-llama31-8b
spec:
  template:
    metadata:
      name: nim-llama-31-8b-dl-pod
    spec:
      containers:
      - args:
        - download-to-cache
        - --profile
        - 8af967d80ae8f30f4635a59b2140fdc2b38d3004e16e66c9667fa032e56497fd
        env:
        - name: NIM_CACHE_PATH
          value: /mnt/models
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              key: NGC_API_KEY
              name: nvidia-nim-secrets
        image: 10.14.75.21/ezmeral-common/nvcr.io/nim/meta/llama-3.1-8b-instruct-pb24h2:1.3.2
        name: nim-profile-single
        volumeMounts:
        - mountPath: /mnt/models
          name: model-cache
      imagePullSecrets:
      - name: ngc-secret
      restartPolicy: Never
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: cache-pvc
