apiVersion: v1
kind: Pod
metadata:
  name: list-profiles-llama-31-8b
spec:
  containers:
  - name: list-profiles-llama-31-8b
    image: 172.28.1.96/ezmeral-common/nvcr.io/nim/meta/llama-3.1-70b-instruct-pb24h2:1.3.1
   # image: 10.14.75.21/ezmeral-common/nvcr.io/nim/meta/llama-3.1-8b-instruct-pb24h2:1.3.2 	
    command: ["list-model-profiles"]
    env:
    - name: NGC_API_KEY
      valueFrom:
        secretKeyRef:
          name: nvidia-nim-secrets
          key: NGC_API_KEY
  restartPolicy: Never
  imagePullSecrets:
  - name: ngc-secret
