[ssh]
host_ip = "172.28.1.62"
username = "pcadmin"
password = ""

[api_keys]
hugging_face_token = ""
ngc_api_key = ""
ngc_token = ""


[pvc_details]
pvc_yaml_path = "/home/pcadmin/cloudai/nim-deploy/kserve/scripts/pv.yaml"
storage_class = "gl4f-filesystem"
storage_size = "1024Gi"

[profile_list]
yaml_path = "/home/pcadmin/cloudai/nim-deploy/kserve/scripts/llama-3.1-8b-instruct.yaml"

[profile]
pod_prefix = "list-profiles-llama-31-8b"
pattern = "l40s-bf16-tp1-pp1-throughput"
image = "10.14.75.21/ezmeral-common/nvcr.io/nim/meta/llama-3.1-8b-instruct-pb24h2:1.3.2"
selected_model_id = "8af967d80ae8f30f4635a59b2140fdc2b38d3004e16e66c9667fa032e56497fd"

[download]
download_yaml = "/home/pcadmin/cloudai/nim-deploy/kserve/scripts/download_l40s-tp1-pp1.yaml"

[paths]
runtime = "/home/pcadmin/cloudai/nim-deploy/kserve/scripts/runtime-l40s-tp1-pp1.yaml"
deploy = "/home/pcadmin/cloudai/nim-deploy/kserve/scripts/deploy-l40s-tp1-pp1.yaml"
workdir_pvc = "/home/pcadmin/cloudai/nim-deploy/kserve/scripts/workdir_pvc.yaml"
genai_pod_yaml = "/home/pcadmin/cloudai/nim-deploy/kserve/scripts/genai-perf-pod.yaml"
shell_script = "/workdir/llama-3.1-70b-instruct/nim_1.3.2/throughput-bf16-tp1-pp1/bench.sh"

[values]
cluster_ip = "10.102.196.71"

[final_exec]
model = "meta/llama-3.1-8b-instruct"
measurement_interval = "300000"
tokenizer = "meta-llama/Llama-3.1-8B-Instruct"
export_file_name = "test1-madhu"
concurrency_values = "1,2,4,8,16,32,64,128,256,512,1024"
use_cases = "Search,Summarization,Translation"
artifacts_dir = "artifacts"
